# Generated by Django 4.2.7 on 2023-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='blog')),
            ],
        ),
    ]
