# Generated by Django 4.2.7 on 2023-12-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
